In [1]:
## 12 다중머신과 장치를 위한 분산 텐서플로 ##
import tensorflow as tf

In [2]:
!nvidia-smi

Tue Nov 24 20:04:14 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 451.67       Driver Version: 451.67       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106... WDDM  | 00000000:06:00.0  On |                  N/A |
|  0%   29C    P5    14W / 120W |    514MiB /  3072MiB |      9%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU  

In [4]:
## GPU 메모리 관리 ##
#1번 방법
config = tf.ConfigProto()
config.gpu_options.allow_growth = True #메모리 수요에 따라 할당

'''주의할 점은, 이 옵션은 메모리의 증식만 가능하다는 것. 연산이 끝나고 메모리가 필요없는 상황이라고 해서 할당된 메모리를 반납하지 않는다. 

Tensorflow 측에서는 그럴 경우 더 심한 메모리 파편화를 일으킬 수도 있다고 하니 판단은 독자의 몫.'''

'주의할 점은, 이 옵션은 메모리의 증식만 가능하다는 것. 연산이 끝나고 메모리가 필요없는 상황이라고 해서 할당된 메모리를 반납하지 않는다. \n\nTensorflow 측에서는 그럴 경우 더 심한 메모리 파편화를 일으킬 수도 있다고 하니 판단은 독자의 몫.'

In [ ]:
## GPU 메모리 관리 ##
#2번 방법
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.3 #메모리 할당 비율 설정
#config.gpu_options.allow_growth = True #메모리 수요에 따라 할당, 두개 같이 사용 가능(추천하지는 않음)

In [ ]:
config.log_device_placement = True #배치자가 노드를 배치할 때마다 메세지 기록

In [4]:
tf.reset_default_graph()

with tf.device("/cpu:0"): #변수 a와 b를 cpu에 할당
    a = tf.Variable(3.0)
    b = tf.Variable(4.0)
    
c = a * b #c는 어떤 장치에도 할당되지 않았으므로 기본장치에 배치됨

with tf.Session(config=config) as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(c))

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:06:00.0, compute capability: 6.1

12.0


In [7]:
## 동적배치함수 ##
def variables_on_cpu(op): #연산이 할당될 장치이름 반환
    if op.type == "Variable":
        return "/cpu:0"
    else:
        return "/gpu:0"

tf.reset_default_graph()

with tf.device(variables_on_cpu):
    a = tf.Variable(3.0) #타입이 Variable이므로 cpu에 할당됨
    b = tf.Variable(4.0) #타입이 Variable이므로 cpu에 할당됨
    #b = tf.Variable(4) #gpu에는 int32형 변수 할당불가능
    c = a * b 
    
with tf.Session(config=config) as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(c))

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:06:00.0, compute capability: 6.1

12.0


In [18]:
## 간접배치 ##
tf.reset_default_graph()

config.allow_soft_placement = True #처리할 커널이 없는 장치에 할당했을 때 cpu로 처리할수 있도록 함

In [19]:
tf.reset_default_graph()

with tf.device("/gpu:0"):
    b = tf.Variable(4) #cpu에 할당될 것임
    
with tf.Session(config=config) as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(b))

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:06:00.0, compute capability: 6.1

4


In [22]:
## 제어의존성 ##
tf.reset_default_graph()

a = tf.Variable(1.0)
b = a + 2.0

with tf.control_dependencies([a, b]): #a,b가 평가된 두 x, y가 평가되게 함
    x = tf.constant(3.0)
    y = tf.constant(4.0)

z = x * y * b

with tf.Session(config=config) as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(z))

Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:06:00.0, compute capability: 6.1

36.0


In [6]:
## 12.2. 다중 머신의 다중 장치 ##
'''
클러스터 : 1개 이상의 태스크, 보통 여러 머신에 나뉘어 있음
태스크 : 하나의 잡에 속함, 하나의 잡은 이름이 부여된 태스크의 그룹(워커 / 파라미터 서버)
'''

'\n클러스터 : 1개 이상의 태스크, 보통 여러 머신에 나뉘어 있음\n태스크 : 하나의 잡에 속함, 하나의 잡은 이름이 부여된 태스크의 그룹(워커 / 파라미터 서버)\n'

<h2>로컬 서버</h2>

In [2]:
c = tf.constant("Hello distributed TensorFlow!")
server = tf.train.Server.create_local_server() #in-process 서버 형태로 단일 프로세스 클러스터를 생성
with tf.Session(server.target) as sess:
    print(sess.run(c))

b'Hello distributed TensorFlow!'


<h2>클러스터</h2>

In [2]:
#클러스터 명세

cluster_spec = tf.train.ClusterSpec({
    "ps":[
        "127.0.0.1:2221",  # /job:ps/task:0
        "127.0.0.1:2222",  # /job:ps/task:1
    ],
    "worker":[
        "127.0.0.1:2223",  # /job:worker/task:0
        "127.0.0.1:2224",  # /job:worker/task:1
        "127.0.0.1:2225",  # /job:worker/task:2
    ]})

# $ CUDA_VISIBLE_DEVICES="" python my_script.py # CPU만 사용하겠다는 뜻(파라미터 서버 설정)

In [3]:
task_ps0 = tf.train.Server(cluster_spec, job_name="ps", task_index=0) #첫번째 "ps" 태스크를 시작
task_ps1 = tf.train.Server(cluster_spec, job_name="ps", task_index=1) #두번째 "ps" 태스크를 시작
task_worker0 = tf.train.Server(cluster_spec, job_name="worker", task_index=0) #첫번째 "worker" 태스크를 시작
task_worker1 = tf.train.Server(cluster_spec, job_name="worker", task_index=1) #두번째 "worker" 태스크를 시작
task_worker2 = tf.train.Server(cluster_spec, job_name="worker", task_index=2) #세번째 "worker" 태스크를 시작

#server.join() #만약 서버를 실행하기만 하는 프로세스라면 다른서버가 종료될 때 까지 서버가 종료되지 않게 해야 함,
#실제로는 서버를 중지시키는 방법은 없기때문에 영원히 블록됨

<h2>장치와 서버간 파이프라이닝</h2>

In [12]:
tf.reset_default_graph()

with tf.device("/job:ps"): #ps잡의 1번째 태스크의 기본장치(cpu0)에 할당됨
    a = tf.Variable(1.0, name="a")

with tf.device("/job:worker/task:0"): #worker잡의 1번째 태스크의 기본장치(gpu0)에 할당됨
    b = a + 2
    
with tf.device("/job:worker/task:1/gpu:0"): #worker잡의 2번째 태스크의 1번째 gpu에 할당됨
    c = a + b
    
d = c * 2 #자신의 기본 장치에 할당됨

with tf.Session("grpc://127.0.0.1:2221") as sess:
    sess.run(a.initializer)
    print(d.eval())

8.0


In [30]:
tf.reset_default_graph()

with tf.device(tf.train.replica_device_setter( #라운드로빈 방식으로 변수들을 각 서버에 분산시킴
        ps_tasks=2, #ps태스크의 수, cluster=cluster_spec를 지정해서 ps잡에 있는 태스크의 수를 찾게 할수도 있음
        ps_device="/job:ps", #파마리터 서버 태스크 지정
        worker_device="/job:worker")): #워커 잡의 장치 지정
    v1 = tf.Variable(1.0, name="v1")  # pinned to /job:ps/task:0 (defaults to /cpu:0)
    v2 = tf.Variable(2.0, name="v2")  # pinned to /job:ps/task:1 (defaults to /cpu:0)
    v3 = tf.Variable(3.0, name="v3")  # pinned to /job:ps/task:0 (defaults to /cpu:0)
    s = v1 + v2            # pinned to /job:worker (defaults to task:0/cpu:0)
    with tf.device("/task:1"):
        p1 = 2 * s         # pinned to /job:worker/task:1 (defaults to /cpu:0)
        with tf.device("/cpu:0"):
            p2 = 3 * s     # pinned to /job:worker/task:1/cpu:0

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session("grpc://127.0.0.1:2221", config=config) as sess:
    sess.run([v1.initializer, v2.initializer, v3.initializer])

with tf.Session("grpc://127.0.0.1:2223", config=config) as sess:
    print(sess.run(p2))

9.0


<h2> 리소스 컨테이너를 사용해 여러 세션에서 상태 공유하기 </h2>

In [41]:
import sys

x = tf.Variable(0.0, name="x") #같은 클러스터에 있는 다른 세션에서 사용 가능
increment_x = tf.assign(x, x+1)

#init
with tf.Session("grpc://127.0.0.1:2223") as sess:
    sess.run(x.initializer)
    sess.run(increment_x)
    print(x.eval())

1.0


In [42]:
#다른 세션에서 같은 클러스터에 있는 변수 사용
with tf.Session("grpc://127.0.0.1:2224") as sess:
    sess.run(increment_x)
    print(x.eval())

with tf.Session("grpc://127.0.0.1:2225") as sess:
    sess.run(increment_x)
    print(x.eval())

2.0
3.0


In [16]:
#컨테이너 사용

tf.reset_default_graph()

#init
with tf.Session("grpc://127.0.0.1:2223") as sess:
    x_share = tf.Variable(1.0, name="x_share")
    increment_x_share = tf.assign(x_share, x_share+1)
    with tf.container("myProblem"):
        x = tf.Variable(10.0, name="x") #같은 클러스터에 있는 다른 세션에서 사용 가능
        increment_x = tf.assign(x, x+1)
    
    sess.run(x.initializer)
    sess.run(increment_x)
    print(x.eval())
    
    ###같은 클러스터 내에서 공유 가능한 변수###
    sess.run(x_share.initializer)
    sess.run(increment_x_share)
    print(x_share.eval())
    
tf.Session.reset("grpc://127.0.0.1:2223", ["myProblem"]) #myProblem 이름을 가진 컨테이너 리셋(컨테이너가 사용하는 모든 리소스 해제)
      
with tf.Session("grpc://127.0.0.1:2224") as sess:
    #sess.run(increment_x) #접근 불가능, 리소스  해제 됨
    
    ###같은 클러스터 내에서 공유 가능한 변수###
    sess.run(increment_x_share)
    print(x_share.eval())

11.0
2.0
3.0


<h2>텐서플로 큐를 사용한 비동기 통신</h2>

![텐서플로우 큐](img/queue.png)

In [5]:
#데이터 로더

q = tf.FIFOQueue(capacity=10, dtypes=[tf.float32], shapes=[[2]], name="q", shared_name="shared_q") #FIRO 큐 생성
#큐가 공유하기 위해서 shared_name을 사용, 물론 같은 컨테이너를 사용해야함
training_instance = tf.placeholder(tf.float32, shape=(2)) #데이터가 담길 변수
enqueue = q.enqueue([training_instance]) #큐에 데이터 집어넣음

with tf.Session("grpc://127.0.0.1:2223") as sess:
    sess.run(enqueue, feed_dict={training_instance: [1., 2.]}) #큐에 데이터 집어넣음
    sess.run(enqueue, feed_dict={training_instance: [3., 4.]}) #큐에 데이터 집어넣음
    sess.run(enqueue, feed_dict={training_instance: [5., 6.]}) #큐에 데이터 집어넣음
    #sess.run(q.close()) #더 이상 데이터가 추가되지 않을 큐를 종료
    #sess.run(q.close(cancel_pending_enqueues=True)) #대기 중인 enqueue 요청 무시

In [6]:
#위와 동일

tf.reset_default_graph()

q = tf.FIFOQueue(capacity=10, dtypes=[tf.float32], shapes=[[2]], name="q", shared_name="shared_q") #FIRO 큐 생성
training_instances = tf.placeholder(tf.float32, shape=(None, 2)) #데이터가 담길 변수
enqueue = q.enqueue_many([training_instances]) #큐에 데이터를 한번에 많이 집어넣음

with tf.Session("grpc://127.0.0.1:2223") as sess:
    sess.run(enqueue, feed_dict={training_instances: [[1., 2.], [3., 4.], [5., 6.]]}) #큐에 데이터를 한번에 많이 집어넣음
    sess.run(q.close()) #더 이상 데이터가 추가되지 않을 큐를 종료
    #sess.run(q.close(cancel_pending_enqueues=True)) #대기 중인 enqueue 요청 무시

In [7]:
#데이터 추출

q = tf.FIFOQueue(capacity=10, dtypes=[tf.float32], shapes=[[2]], name="q", shared_name="shared_q") #FIRO 큐 생성
dequeue_mini_batch = q.dequeue() #큐에서 데이터 뽑음

with tf.Session("grpc://127.0.0.1:2224") as sess:
    print(sess.run(dequeue_mini_batch))
    print(sess.run(dequeue_mini_batch))
    print(sess.run(dequeue_mini_batch))

[1. 2.]
[3. 4.]
[5. 6.]


In [8]:
#위와 동일

q = tf.FIFOQueue(capacity=10, dtypes=[tf.float32], shapes=[[2]], name="q", shared_name="shared_q") #FIRO 큐 생성
batch_size = 2
#dequeue_mini_batch = q.dequeue_many(batch_size) #큐에서 배치사이즈 만큼 데이터 뽑음, 데이터가 모자라면 다른 샘플이 올 때 까지 대기
dequeue_mini_batch = q.dequeue_up_to(batch_size) #큐에서 배치사이즈 만큼 데이터 뽑음, 데이터가 모자라면 나머지라도 긁어서 옴

with tf.Session("grpc://127.0.0.1:2224") as sess:
    print(sess.run(dequeue_mini_batch))
    print(sess.run(dequeue_mini_batch))

'''
큐가 꽉차면 enqueue 연산은 dequeue 연산으로 큐에 남는 자리가 생길 때 까지 대기
큐가 비어있거나 dequeue_many 의 미니배치 사이즈보다 큐에 있는 아이템의 수가 적으면 enqueue 연산으로 데이터 들어올 때 까지 대기
'''

[[1. 2.]
 [3. 4.]]
[[5. 6.]]


'\n큐가 꽉차면 enqueue 연산은 dequeue 연산으로 큐에 남는 자리가 생길 때 까지 대기\n큐가 비어있거나 dequeue_many 의 미니배치 사이즈보다 큐에 있는 아이템의 수가 적으면 enqueue 연산으로 데이터 들어올 때 까지 대기\n'

In [15]:
#튜플 큐 (큐에 있는 아이템이 하나의 텐서 대신 텐서의 튜플)

tf.reset_default_graph()

tq = tf.FIFOQueue(capacity=10, dtypes=[tf.int32, tf.float32], shapes=[[], [3, 2]],
                 name="tq", shared_name="shaed_tq")

a = tf.placeholder(tf.int32, shape=())
b = tf.placeholder(tf.float32, shape=(3, 2))
enqueue = tq.enqueue((a, b))

with tf.Session("grpc://127.0.0.1:2224") as sess:
    sess.run(enqueue, feed_dict={a: 10, b: [[1., 2.], [3., 4.], [5., 6.]]})
    sess.run(enqueue, feed_dict={a: 20, b: [[21., 22.], [23., 24.], [25., 26.]]})
    sess.run(enqueue, feed_dict={a: 30, b: [[31., 32.], [33., 34.], [35., 36.]]})
    sess.run(tq.close())

In [16]:
t_dequeue_a, t_dequeue_b = tq.dequeue()

with tf.Session("grpc://127.0.0.1:2223") as sess:
    a_val, b_val = sess.run([t_dequeue_a, t_dequeue_b])
    print(a_val)
    print(b_val)

10
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [17]:
batch_size = 3
t_dequeue_as, t_dequeue_bs = tq.dequeue_up_to(batch_size)

with tf.Session("grpc://127.0.0.1:2223") as sess:
    a_val, b_val = sess.run([t_dequeue_as, t_dequeue_bs])
    print(a_val)
    print(b_val)

[20 30]
[[[21. 22.]
  [23. 24.]
  [25. 26.]]

 [[31. 32.]
  [33. 34.]
  [35. 36.]]]


In [6]:
#아이템을 랜덤하게 변환하여 반환하는 큐
r_q = tf.RandomShuffleQueue(capacity=50, min_after_dequeue=10, #큐에 남아있어야 하는 최소 아이템의 수 10개
                           dtypes=[tf.float32], shapes=[()],
                           name="r_q", shared_name="shared_r_q")

#크기가 다른 텐서를 받는 큐
p_q = tf.PaddingFIFOQueue(capacity=50, dtypes=[tf.float32],
                         shapes=[(None, None)], name="r_q",
                         shared_name="shared_r_q")
v = tf.placeholder(tf.float32, shape=(None, None))
p_enqueue = p_q.enqueue([v])

with tf.Session("grpc://127.0.0.1:2222") as sess:
    sess.run(p_enqueue, feed_dict={v: [[1., 2.], [3., 4.], [5., 6.]]}) #3*2 텐서
    sess.run(p_enqueue, feed_dict={v: [[1., 2., 3., 4.], [5., 6., 7., 8.]]}) #2*4 텐서
    sess.run(p_enqueue, feed_dict={v: [[1., 2.], [3., 4.], [5., 6.], [7., 8.], [9., 10.]]}) #5*2 텐서
    sess.run(p_q.close())

<h2>그래프에서 직접 데이터 로드하기</h2>

In [12]:
#데이터에 변수 프리로드
'''
메모리가 충분하다면 훈련 데이터를 한번에 로드해서 변수에 할당 후 그래프에서 이 변수를 바로 사용
'''

tf.reset_default_graph()

data_len = 1
n_features = 3
training_set_init = tf.placeholder(tf.float32, shape=(data_len, n_features))
training_set = tf.Variable(training_set_init,
                          trainable=False, #옵티마이저가 이 변수를 수정하지 못하도록 함
                          collections=[],   #이 변수가 체크포인트 저장이나 복원에 사용되는 GraphKeys.GLOBAL_VARIABLES 컬렉션에 추가되지 않도록 함
                          name="training_set")

In [22]:
#그래프에서 직접 훈련 데이터 읽기

tf.reset_default_graph()

'''
test_csv = open("my_test.csv", "w")
test_csv.write("x1, x2 , target\n")
test_csv.write("1.,, 0\n")
test_csv.write("4., 5. , 1\n")
test_csv.write("7., 8. , 0\n")
test_csv.close()
'''

reader = tf.TextLineReader(skip_header_lines=1) #파일을 열고 한줄씩 읽음, 헤더 무시

filename_queue = tf.FIFOQueue(capacity=10, dtypes=[tf.string], shapes=[()])
filename = tf.placeholder(tf.string)
enqueue_filename = filename_queue.enqueue([filename])
close_filename_queue = filename_queue.close()

key, value = reader.read(filename_queue) #한번에 하나의 레코드를 읽어서 키/값 쌍을 반환

x1, x2, target = tf.decode_csv(value, record_defaults=[[-1.], [-1.], [-1]])
features = tf.stack([x1, x2]) #스택

instance_queue = tf.RandomShuffleQueue(capacity=10, min_after_dequeue=2,
                                      dtypes=[tf.float32, tf.int32], shapes=[[2], []],
                                      name="instance_q", shared_name="shared_instance_q")
enqueue_instance = instance_queue.enqueue([features, target])
close_instance_queue = instance_queue.close()

minibatch_instances, minibatch_targets = instance_queue.dequeue_up_to(2)

with tf.Session("grpc://127.0.0.1:2222") as sess:
    sess.run(enqueue_filename, feed_dict={filename: "my_test.csv"})
    sess.run(close_filename_queue)
    
    try:
        while True:
            sess.run(enqueue_instance) #더이상 읽을 데이터가 없으면 OutOfRangeError 발생
    except tf.errors.OutOfRangeError as ex:
            pass
    sess.run(close_instance_queue)
    
    ##훈련 데이터 추출##
    try:
        while True:
            print(sess.run([minibatch_instances, minibatch_targets]))
    except tf.errors.OutOfRangeError as ex:
        pass

[array([[1., 2.],
       [4., 5.]], dtype=float32), array([0, 1])]
[array([[ 7., -1.]], dtype=float32), array([0])]


In [41]:
#그래프에서 직접 훈련 데이터 읽기 NEW 버전

def decode_csv_line(line):
    x1, x2, y = tf.decode_csv(
        line, record_defaults=[[-1.], [-1.], [-1]])
    X = tf.stack([x1, x2])
    return X, y

In [55]:
tf.reset_default_graph()

'''
test_csv = open("my_test.csv", "w")
test_csv.write("x1, x2 , target\n")
test_csv.write("1.,, 0\n")
test_csv.write("4., 5. , 1\n")
test_csv.write("7., 8. , 0\n")
test_csv.close()
'''

filename_queue = tf.FIFOQueue(capacity=10, dtypes=[tf.string], shapes=[()])
filename = tf.placeholder(tf.string)
enqueue_filename = filename_queue.enqueue([filename])
close_filename_queue = filename_queue.close()

dataset = tf.data.TextLineDataset("my_test.csv").skip(1).map(decode_csv_line)

it = dataset.make_one_shot_iterator()
features, target = it.get_next()

instance_queue = tf.RandomShuffleQueue(capacity=10, min_after_dequeue=2,
                                      dtypes=[tf.float32, tf.int32], shapes=[[2], []],
                                      name="instance_q", shared_name="shared_instance_q")
enqueue_instance = instance_queue.enqueue([features, target])
close_instance_queue = instance_queue.close()

minibatch_instances, minibatch_targets = instance_queue.dequeue_up_to(2)

with tf.Session() as sess:
    sess.run(enqueue_filename, feed_dict={filename: "my_test.csv"})
    sess.run(close_filename_queue)
    
    try:
        while True:
            sess.run(enqueue_instance) #더이상 읽을 데이터가 없으면 OutOfRangeError 발생
    except tf.errors.OutOfRangeError as ex:
            pass
    sess.run(close_instance_queue)
    
    ##훈련 데이터 추출##
    try:
        while True:
            print(sess.run([minibatch_instances, minibatch_targets]))
    except tf.errors.OutOfRangeError as ex:
        pass

[array([[ 7., -1.],
       [ 4.,  5.]], dtype=float32), array([0, 1])]
[array([[1., 2.]], dtype=float32), array([0])]


<h2>Queue runners 와 coordinators</h2>

In [2]:
#멀티스레드 큐 사용

tf.reset_default_graph()

filename_queue = tf.FIFOQueue(capacity=10, dtypes=[tf.string], shapes=[()])
filename = tf.placeholder(tf.string)
enqueue_filename = filename_queue.enqueue([filename])
close_filename_queue = filename_queue.close()

reader = tf.TextLineReader(skip_header_lines=1)
key, value = reader.read(filename_queue)

x1, x2, target = tf.decode_csv(value, record_defaults=[[-1.], [-1.], [-1]])
features = tf.stack([x1, x2])

instance_queue = tf.RandomShuffleQueue(
    capacity=10, min_after_dequeue=2,
    dtypes=[tf.float32, tf.int32], shapes=[[2],[]],
    name="instance_q", shared_name="shared_instance_q")
enqueue_instance = instance_queue.enqueue([features, target])
close_instance_queue = instance_queue.close()

minibatch_instances, minibatch_targets = instance_queue.dequeue_up_to(2)

n_threads = 2
queue_runner = tf.train.QueueRunner(instance_queue, [enqueue_instance] * n_threads)

with tf.Session() as sess:
    sess.run(enqueue_filename, feed_dict={filename: "my_test.csv"})
    sess.run(close_filename_queue)
    coord = tf.train.Coordinator() #여러개의 스레드 중지 조정
    enqueue_threads = queue_runner.create_threads(sess, coord=coord, start=True)
    
    try:
        while not coord.should_stop(): #스레드를 중지 요청이 올때까지 반복
            print(sess.run([minibatch_instances, minibatch_targets]))
    except tf.errors.OutOfRangeError as ex:
        coord.request_stop() #모든 스레드를 멈추도록 요청
    
    coord.join(enqueue_threads) #모든 스레드가 종료될 때 까지 기다림

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
[array([[ 7., -1.],
       [ 1.,  2.]], dtype=float32), array([0, 0])]
[array([[4., 5.]], dtype=float32), array([1])]


In [3]:
#여러개의 파일로부터 동시에 읽기

def read_and_push_instance(filename_queue, instance_queue):
    reader = tf.TextLineReader(skip_header_lines=1)
    key, value = reader.read(filename_queue)
    x1, x2, target = tf.decode_csv(value, record_defaults=[[-1.], [-1.], [-1]])
    features = tf.stack([x1, x2])
    enqueue_instance = instance_queue.enqueue([features, target])
    return enqueue_instance

In [11]:
tf.reset_default_graph()

filename_queue = tf.FIFOQueue(capacity=10, dtypes=[tf.string], shapes=[()])
filename = tf.placeholder(tf.string)
enqueue_filename = filename_queue.enqueue([filename])
close_filename_queue = filename_queue.close()

instance_queue = tf.RandomShuffleQueue(
    capacity=10, min_after_dequeue=2,
    dtypes=[tf.float32, tf.int32], shapes=[[2],[]],
    name="instance_q", shared_name="shared_instance_q")

minibatch_instances, minibatch_targets = instance_queue.dequeue_up_to(2)

read_and_enqueue_ops = [read_and_push_instance(filename_queue, instance_queue) for i in range(3)]
queue_runner = tf.train.QueueRunner(instance_queue, read_and_enqueue_ops) #(큐, 스레드에서 실행될 큐 옵션)

with tf.Session() as sess:
    sess.run(enqueue_filename, feed_dict={filename: "my_test.csv"})
    sess.run(enqueue_filename, feed_dict={filename: "my_test1.csv"})
    sess.run(enqueue_filename, feed_dict={filename: "my_test2.csv"})
    sess.run(close_filename_queue)
    coord = tf.train.Coordinator() #여러개의 스레드 중지 조정
    enqueue_threads = queue_runner.create_threads(sess, coord=coord, start=True)
    try:
        while not coord.should_stop(): #스레드를 중지 요청이 올때까지 반복
            print(sess.run([minibatch_instances, minibatch_targets]))
    except tf.errors.OutOfRangeError as ex:
        coord.request_stop() #모든 스레드를 멈추도록 요청
    
    coord.join(enqueue_threads) #모든 스레드가 종료될 때 까지 기다림

[array([[4., 5.],
       [1., 2.]], dtype=float32), array([1, 0])]
[array([[1. , 2. ],
       [4.4, 9.9]], dtype=float32), array([0, 1])]
[array([[ 7., -1.],
       [ 4.,  5.]], dtype=float32), array([0, 1])]
[array([[ 1. ,  7.2],
       [ 7. , -1. ]], dtype=float32), array([0, 0])]
[array([[ 8., -1.]], dtype=float32), array([1])]


<h2>텐서플로 클러스터에서 신경망 병렬화하기</h2>

In [9]:
#타임아웃 설정

tf.reset_default_graph()

q = tf.FIFOQueue(capacity=10, dtypes=[tf.float32], shapes=[()])
v = tf.placeholder(tf.float32)
enqueue = q.enqueue([v])
dequeue = q.dequeue()
output = dequeue + 1

#방법1
with tf.Session() as sess:
    run_options = tf.RunOptions()
    run_options.timeout_in_ms = 1000 #1초 타임아웃
    
    sess.run(enqueue, feed_dict={v: 1.0})
    sess.run(enqueue, feed_dict={v: 2.0})
    sess.run(enqueue, feed_dict={v: 3.0})
    sess.run(q.close())
    print(sess.run(output, options=run_options)) #run옵션으로 타임아웃 설정
    print(sess.run(output, feed_dict={dequeue: 5}, options=run_options)) #run옵션으로 타임아웃 설정
    print(sess.run(output, options=run_options)) #run옵션으로 타임아웃 설정
    print(sess.run(output, options=run_options)) #run옵션으로 타임아웃 설정
    try:
        print(sess.run(output))
    except tf.errors.DeadlineExceededError as ex:
        print("Timed out while dequeuing")
    except tf.errors.OutOfRangeError as ex:
        pass

2.0
6.0
3.0
4.0


In [5]:
#타임아웃 설정

tf.reset_default_graph()

q = tf.FIFOQueue(capacity=10, dtypes=[tf.float32], shapes=[()])
v = tf.placeholder(tf.float32)
enqueue = q.enqueue([v])
dequeue = q.dequeue()
output = dequeue + 1

#방법2
config = tf.ConfigProto()
config.operation_timeout_in_ms = 1000 #1초 타임아웃

with tf.Session(config=config) as sess:
    sess.run(enqueue, feed_dict={v: 1.0})
    sess.run(enqueue, feed_dict={v: 2.0})
    sess.run(enqueue, feed_dict={v: 3.0})
    sess.run(q.close())
    print(sess.run(output))
    print(sess.run(output, feed_dict={dequeue: 5}))
    print(sess.run(output))
    print(sess.run(output))
    try:
        print(sess.run(output))
    except tf.errors.DeadlineExceededError as ex:
        print("Timed out while dequeuing")
    except tf.errors.OutOfRangeError as ex:
        pass

2.0
6.0
3.0
4.0
